In [2]:
# Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성
# A.
import numpy as np
ar = np.arange(10)
ar1 = ar.reshape(-1,)
ar2 = ar.reshape(2,-1)
ar3 = ar.reshape(-1,2,5)
print(ar1)
print(ar2)
print(ar3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [3]:
# 리스트와 모습은 거의 비슷하지만 튜플에서는 리스트와 다른 2가지 차이점을 찾아볼 수 있다. 
# t2 = (1,)처럼 단지 1개의 요소만을 가질 때는 요소 뒤에 콤마(,)를 반드시 붙여야 한다는 것과 
# t4 = 1, 2, 3처럼 괄호( )를 생략해도 무방하다는 점이다.
# Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환
# 1 -> 2,3 차원
# A.
ar12 = ar1.reshape(2,-1)
ar13 = ar1.reshape(-1,2,5)
print(ar12)
print(ar13)
print()
ar21 = ar2.reshape(-1,)
ar23 = ar2.reshape(-1,2,5)
print(ar21)
print(ar23)
print()
ar31 = ar3.reshape(-1,)
ar32 = ar3.reshape(2,-1)
print(ar31)
print(ar32)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]

[0 1 2 3 4 5 6 7 8 9]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
# Q3. 1차원 배열을 실수형으로 변환
# Q4. 1차원 배열의 dtype을 확인
# A.
ar1_float = ar1.astype('float64')
print(ar1_float, ar1_float.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [4]:
# Q5. str.format을 사용하여 출력
# A.
print("array1 : {}차원, array2 : {}차원, array3 : {}차원".format(ar1.ndim,ar2.ndim,ar3.ndim))

array1 : 1차원, array2 : 2차원, array3 : 3차원


In [5]:
# Q. array2d에서 슬라이싱을 사용해서 아래와 같이 출력하세요.
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

In [6]:
# A.
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print()
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print()
print('array2d[:, :] \n', array2d[:, :])
print()
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print()
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]

array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]

array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[:2, 1:] 
 [[2 3]
 [5 6]]

array2d[:2, 0] 
 [1 4]


In [7]:
# Q. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력
# A.
a1 = np.arange(100)
a2 = a1[a1 % 3 ==0]
a2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Q. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력
# A.
import numpy as np
a1 = np.arange(100)
a1 = a1[(a1 % 5 ==0) & (a1 % 2==0)]
a1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [2]:
# Q. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력
# A.
import numpy as np
a1 = np.arange(100)
# print(a1)
        
a1 = a1[(a1 % 3 ==0) | (a1 % 5==0)]
a1

array([ 0,  3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35,
       36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70,
       72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99])

In [17]:
# Q. (3,3) 25 ~ 50 정수
# A. 
a1 = np.random.randint(25,51, size=(3,3))
print(a1)

[[46 45 36]
 [49 45 48]
 [40 30 32]]


In [18]:
# Q. (2,5) 101 ~ 150 정수, 전치
# A. 
a1 = np.random.randint(101,151, size=(2,5))
print(a1)
print()
a1_t=np.transpose(a1)
print(a1_t)

[[103 133 105 112 150]
 [102 149 148 139 105]]
[[103 102]
 [133 149]
 [105 148]
 [112 139]
 [150 105]]


In [22]:
# Q. (5,5) 0 ~ 10 정수, 역행렬
# A. 
a1 = np.random.randint(11, size=(5,5))
print(a1)
print("역행렬")
a1_r=np.linalg.inv(a1)
print(a1_r)
print("행렬곱")
a2 = np.dot(a1,a1_r)
print(a2)

[[ 4  3  4  1 10]
 [ 6  2  3  0  4]
 [ 2  0  5 10  7]
 [ 8  0  1  0 10]
 [ 1 10  4  7  1]]
역행렬
[[-0.15148862  0.14404553  0.00350263  0.08975482  0.01663748]
 [ 0.02864648 -0.06398549 -0.07580686  0.03959219  0.10420315]
 [ 0.14110583  0.27870903  0.05454091 -0.28096072 -0.09807356]
 [-0.11521141 -0.06798849  0.07780836  0.08312484  0.04816112]
 [ 0.10708031 -0.14310733 -0.00825619  0.05629222 -0.00350263]]
행렬곱
[[ 1.00000000e+00 -5.55111512e-17  8.32667268e-17 -8.32667268e-17
  -2.86229374e-17]
 [ 5.55111512e-17  1.00000000e+00  6.93889390e-17 -5.55111512e-17
  -8.67361738e-18]
 [ 0.00000000e+00 -1.94289029e-16  1.00000000e+00  4.16333634e-17
   1.25767452e-17]
 [ 0.00000000e+00 -5.55111512e-17  0.00000000e+00  1.00000000e+00
   6.07153217e-18]
 [ 0.00000000e+00  2.77555756e-17  2.77555756e-17 -5.55111512e-17
   1.00000000e+00]]


In [23]:
# Q. 1차원(원소 5개) 배열 0 ~ 10 정수
# A. 
a1 = np.random.randint(11, size=5)
print(a1)

[ 6  0 10  1 10]


In [43]:
# Q. 숫자 1개 21 ~ 30 정수
# A. 
a1 = np.random.randint(21,31)
a1

24

In [24]:
# Q. 0~1사이의 균일분포 (5,5)
# A.
np.random.rand(5,5)

array([[0.38983835, 0.25604378, 0.9809063 , 0.01059412, 0.91351844],
       [0.12829813, 0.51142517, 0.90952071, 0.6508317 , 0.86937023],
       [0.07855542, 0.53135805, 0.64167161, 0.65361591, 0.78147322],
       [0.45467658, 0.5127654 , 0.81074851, 0.1592577 , 0.56160498],
       [0.51692401, 0.84829973, 0.3112478 , 0.85201577, 0.0062655 ]])

In [25]:
# Q. 표준정규분포 (5,5)
# A.
np.random.randn(5,5)

array([[-0.67438951, -0.76790889,  0.60799196, -1.30982941, -0.10489588],
       [-0.72727038, -0.13315122,  0.72299444,  0.6969418 ,  0.7078546 ],
       [ 0.30958247, -1.69086529, -1.57674654,  0.03943237,  0.9291706 ],
       [-0.1928844 , -0.729683  , -0.59722681,  0.46095317,  0.74749329],
       [-1.00720995,  0.42918588,  0.49333145,  0.81548307,  1.17492998]])

In [ ]:
# Q. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [6]:
ar = np.arange(1,101)
ar3 = ar[ar % 3 == 0]
ar3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Q. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [8]:
ar35 = ar[(ar % 3==0)|(ar%5==0)]
ar35

array([  3,   5,   6,   9,  10,  12,  15,  18,  20,  21,  24,  25,  27,
        30,  33,  35,  36,  39,  40,  42,  45,  48,  50,  51,  54,  55,
        57,  60,  63,  65,  66,  69,  70,  72,  75,  78,  80,  81,  84,
        85,  87,  90,  93,  95,  96,  99, 100])

In [ ]:
# Q. 배열 a를 아래와 같이 생성하세요
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# Q. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [11]:
a = np.random.randint(101,150,size=(2,5))
a.T

array([[119, 147],
       [113, 138],
       [122, 136],
       [124, 132],
       [127, 124]])

In [ ]:
# Q. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [12]:
np.random.randn(5,5)

array([[ 0.32785633,  0.27749804,  0.15834877, -0.28587712,  0.93372636],
       [ 1.44292084, -0.95943154,  0.9752299 , -0.56722888,  1.56207088],
       [-1.48271023, -0.4584417 , -0.81152504, -1.27758423, -0.97172465],
       [ 1.80132015,  0.65404691,  0.61579908, -0.0574461 , -0.16835022],
       [-0.5702344 ,  0.62892388,  1.57414859,  1.53375544, -0.09736572]])