행렬곱을 지원하는 numpy 함수에는 dot과 matmul이 있고, 둘의 행렬곱 결과는 항상 동일하나
3차원 이상의 행렬끼리 곱할 때는 서로 다른 결과를 보여줌
- numpy.dot은 두 배열의 내적곱(dot product)인 반면 numpy matmul은 두 배열의 행렬곱(matrix product)
- a가 N차원 배열이고 b가 2이상의 M차원 배열이라면, dot(a,b)는 a의 마지막 축과 b의 뒤에서 두번째 축과의 내적으로 계산

dot과 matmul 계산방식

<img src = '행렬곱함수.jpg' STYLE = 'width:500px;'>

In [7]:
import numpy as np
a = np.arange(2*3*4).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
b2 = np.arange(2*3*4).reshape((2,4,3))
b4 = np.arange(2*3*4).reshape((3,4,2))
b2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [14]:
# a의 마지막 축과 b의 뒤에서 두번째 축과의 내적으로 계산
np.dot(a,b2)
# np.dot(a,b4)

array([[[[  42,   48,   54],
         [ 114,  120,  126]],

        [[ 114,  136,  158],
         [ 378,  400,  422]],

        [[ 186,  224,  262],
         [ 642,  680,  718]]],


       [[[ 258,  312,  366],
         [ 906,  960, 1014]],

        [[ 330,  400,  470],
         [1170, 1240, 1310]],

        [[ 402,  488,  574],
         [1434, 1520, 1606]]]])

In [12]:
# 각 텐서의 끝에서 2개의 축이 서로 행렬곱 가능한 경우만 matmul이 계산
# 배열 B의 차원이 (5,2,4,3)인 경우, (4x3)행렬을 (5x2)개수만큼 갖는다고 간주
# 배열 C의 차원이 (1,5,3,2,4,6)이라고 한다면, (4x6)행렬을 (1x5x3x2)만큼 갖고 있다는 의미
np.matmul(a,b2)


array([[[  42,   48,   54],
        [ 114,  136,  158],
        [ 186,  224,  262]],

       [[ 906,  960, 1014],
        [1170, 1240, 1310],
        [1434, 1520, 1606]]])

In [13]:
np.matmul(a,b4)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,3,4)->(2,newaxis,newaxis) (3,4,2)->(3,newaxis,newaxis) and requested shape (3,2)